import React, { useState, useEffect, useRef } from 'react';
import {
  Cpu,
  Bot,
  User,
  Send,
  Download,
  Copy,
  ShieldAlert,
  Sparkles,
  RefreshCw,
  Trash2,
  Flame,
} from 'lucide-react';
import type { Language, BaitPersona, HoneypotMessage, IOC, ActivePillar } from '../types';
import { honeypotBaitPersonas } from '../data/karnatakaScamData';
import { mockHoneypotScript, mockIOCs } from '../mockData';

interface ScamHoneypotTrapProps {
  language: Language;
  onNavigateTo: (pillar: ActivePillar) => void;
}

export const ScamHoneypotTrap: React.FC<ScamHoneypotTrapProps> = ({
  language,
  onNavigateTo,
}) => {
  const [selectedPersona, setSelectedPersona] = useState<BaitPersona>(honeypotBaitPersonas[0]);
  const [messages, setMessages] = useState<HoneypotMessage[]>(mockHoneypotScript.slice(0, 4));
  const [isSimulating, setIsSimulating] = useState(false);
  const [currentStepIndex, setCurrentStepIndex] = useState(4);
  const [harvestedIOCs, setHarvestedIOCs] = useState<IOC[]>(mockIOCs.slice(0, 3));
  const [copied, setCopied] = useState(false);
  const [dossierExported, setDossierExported] = useState(false);

  const chatBottomRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    chatBottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleNextStep = () => {
    if (currentStepIndex >= mockHoneypotScript.length) return;

    setIsSimulating(true);
    const nextMsg = mockHoneypotScript[currentStepIndex];

    setTimeout(() => {
      setMessages((prev) => [...prev, nextMsg]);
      setCurrentStepIndex((prev) => prev + 1);

      // If this message has extracted IOC, harvest it
      if (nextMsg.extracted) {
        const newIOC: IOC = {
          id: `ioc-${Date.now()}`,
          type: nextMsg.extracted.type,
          value: nextMsg.extracted.value,
          firstSeen: '2026-08-24',
          lastSeen: '2026-08-24',
          riskScore: 94,
          linkedScamArchetype: 'SBI_YONO_KYC',
          reportCount: 1,
        };
        setHarvestedIOCs((prev) => [newIOC, ...prev]);
      }

      setIsSimulating(false);
    }, 1000);
  };

  const handleAutoRun = () => {
    if (currentStepIndex >= mockHoneypotScript.length) return;
    setIsSimulating(true);

    let idx = currentStepIndex;
    const interval = setInterval(() => {
      if (idx >= mockHoneypotScript.length) {
        clearInterval(interval);
        setIsSimulating(false);
        return;
      }
      const msg = mockHoneypotScript[idx];
      setMessages((prev) => [...prev, msg]);
      if (msg.extracted) {
        setHarvestedIOCs((prev) => [
          {
            id: `ioc-${Date.now()}-${idx}`,
            type: msg.extracted!.type,
            value: msg.extracted!.value,
            firstSeen: '2026-08-24',
            lastSeen: '2026-08-24',
            riskScore: 95,
            linkedScamArchetype: 'SBI_YONO_KYC',
            reportCount: 1,
          },
          ...prev,
        ]);
      }
      idx++;
      setCurrentStepIndex(idx);
    }, 1800);
  };

  const handleResetChat = () => {
    setMessages(mockHoneypotScript.slice(0, 2));
    setCurrentStepIndex(2);
    setHarvestedIOCs(mockIOCs.slice(0, 2));
  };

  const handleExportDossier = () => {
    const dossier = `=== KARNATAKA CID CYBER FORENSIC INCIDENT DOSSIER ===
Generated by: RAKSHA AI Autonomous Honeypot Protocol
Date: ${new Date().toISOString()}
Target Persona: ${selectedPersona.name} (${selectedPersona.role})

HARVESTED INDICATORS OF COMPROMISE (IOCs):
${harvestedIOCs
  .map(
    (ioc, i) =>
      `[${i + 1}] Type: ${ioc.type} | Value: ${ioc.value} | Risk: ${ioc.riskScore}/100 | Archetype: ${ioc.linkedScamArchetype}`
  )
  .join('\n')}

CONVERSATION TRANSCRIPT:
${messages
  .map((m) => `[${m.timestamp}] ${m.sender === 'AGENT' ? `AI BAIT (${selectedPersona.name})` : 'SCAMMER'}: ${m.text}`)
  .join('\n')}

--- END OF DOSSIER (Compliant with 1930 NCRP Evidence Intake) ---`;

    const blob = new Blob([dossier], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `RAKSHA_Honeypot_Dossier_${Date.now()}.txt`;
    a.click();

    setDossierExported(true);
    setTimeout(() => setDossierExported(false), 3000);
  };

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      {/* Header */}
      <div className="mb-6 flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-purple-500/20 text-purple-400">
              <Cpu className="h-4 w-4" />
            </span>
            <h2 className="text-xl font-bold text-slate-100 sm:text-2xl">
              {language === 'kn'
                ? 'AI ಹನಿಪಾಟ್ ಟ್ರ್ಯಾಪ್ & ಮ್ಯೂಲ್ ಖಾತೆ ಬೇಟೆಗಾರ'
                : 'Autonomous AI Honeypot & Syndicate Trap'}
            </h2>
          </div>
          <p className="mt-1 text-xs text-slate-400 sm:text-sm">
            {language === 'kn'
              ? 'ಸ್ವಯಂಚಾಲಿತ AI ಸಂಭಾಷಣಾ ಏಜೆಂಟ್‌ಗಳನ್ನು ವಂಚಕರೊಂದಿಗೆ ತೊಡಗಿಸಿ, ಅವರ UPI, ಬ್ಯಾಂಕ್ ಖಾತೆ ಮತ್ತು ಫೋನ್ ವಿವರಗಳನ್ನು ಹೊರತೆಗೆಯಿರಿ.'
              : 'Deploy autonomous conversational personas to bait scammers, drain criminal bandwidth, and harvest actionable mule accounts.'}
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleExportDossier}
            className="flex items-center gap-1.5 rounded-xl border border-purple-500/40 bg-purple-950/40 px-3.5 py-2 text-xs font-bold text-purple-300 hover:bg-purple-900/50"
          >
            <Download className="h-3.5 w-3.5" />
            <span>{dossierExported ? (language === 'kn' ? 'ಡೌನ್‌ಲೋಡ್ ಆಯಿತು!' : 'Dossier Saved!') : language === 'kn' ? '1930 CID ಡಾಕ್ಯುಮೆಂಟ್ ಎಕ್ಸ್‌ಪೋರ್ಟ್' : 'Export 1930 CID Dossier'}</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-12">
        {/* Left: Persona Selector & Interactive Chat Terminal (7 cols) */}
        <div className="lg:col-span-7 flex flex-col gap-4">
          {/* Persona Card Selector */}
          <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-300 mb-3">
              {language === 'kn' ? 'AI ಬೈಟಿಂಗ್ ಪರ್ಸೋನಾ ಆಯ್ಕೆ (Select Bait Persona)' : 'Deployable Bait Personas'}
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
              {honeypotBaitPersonas.map((persona) => (
                <button
                  key={persona.id}
                  type="button"
                  onClick={() => setSelectedPersona(persona)}
                  className={`flex flex-col items-start rounded-xl border p-3 text-left transition-all ${
                    selectedPersona.id === persona.id
                      ? 'border-purple-500 bg-purple-950/40 text-slate-100 shadow-md shadow-purple-950/30'
                      : 'border-slate-800 bg-slate-950/50 text-slate-400 hover:border-slate-700 hover:text-slate-200'
                  }`}
                >
                  <div className="flex items-center gap-2">
                    <span className="text-xl">{persona.avatar}</span>
                    <div>
                      <div className="text-xs font-bold text-slate-200">
                        {language === 'kn' ? persona.nameKn : persona.name}
                      </div>
                      <div className="text-[10px] text-purple-400 font-mono">
                        {persona.role}
                      </div>
                    </div>
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* Live Chat Stream Terminal */}
          <div className="flex flex-col rounded-2xl border border-slate-800 bg-slate-950/90 overflow-hidden shadow-2xl">
            {/* Terminal Header */}
            <div className="flex items-center justify-between border-b border-slate-800 bg-slate-900/80 px-4 py-2.5">
              <div className="flex items-center gap-2">
                <span className="h-2.5 w-2.5 rounded-full bg-purple-400 animate-ping" />
                <span className="font-mono text-xs font-bold text-slate-200">
                  HONEYPOT LIVE TRAP: {selectedPersona.name} vs SCAMMER
                </span>
              </div>
              <button
                type="button"
                onClick={handleResetChat}
                className="flex items-center gap-1 text-[11px] text-slate-400 hover:text-slate-200"
                title="Reset simulation"
              >
                <Trash2 className="h-3 w-3" />
                <span>Reset</span>
              </button>
            </div>

            {/* Chat Messages */}
            <div className="flex-1 p-4 space-y-3.5 max-h-[420px] overflow-y-auto font-sans text-xs">
              {messages.map((msg) => {
                const isAgent = msg.sender === 'AGENT';
                return (
                  <div
                    key={msg.id}
                    className={`flex flex-col ${isAgent ? 'items-start' : 'items-end'}`}
                  >
                    <div className="flex items-center gap-1.5 mb-1 text-[10px] text-slate-400 font-mono">
                      {isAgent ? (
                        <>
                          <Bot className="h-3 w-3 text-purple-400" />
                          <span className="font-bold text-purple-300">
                            {selectedPersona.name}
                          </span>
                        </>
                      ) : (
                        <>
                          <span className="font-bold text-red-400">SCAMMER (SBI_IMPERSONATOR)</span>
                          <User className="h-3 w-3 text-red-400" />
                        </>
                      )}
                      <span>• {msg.timestamp}</span>
                    </div>

                    <div
                      className={`max-w-[85%] rounded-2xl p-3 leading-relaxed ${
                        isAgent
                          ? 'border border-purple-500/30 bg-purple-950/40 text-purple-100 rounded-tl-sm'
                          : 'border border-red-500/30 bg-red-950/30 text-red-100 rounded-tr-sm'
                      }`}
                    >
                      {msg.text}

                      {msg.extracted && (
                        <div className="mt-2 flex items-center gap-1.5 rounded-lg border border-yellow-500/40 bg-yellow-950/50 px-2 py-1 font-mono text-[11px] font-bold text-yellow-300">
                          <Sparkles className="h-3.5 w-3.5 text-yellow-400" />
                          <span>TRAPPED IOC: [{msg.extracted.type}] {msg.extracted.value}</span>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
              {isSimulating && (
                <div className="flex items-center gap-2 text-xs text-purple-400 animate-pulse font-mono">
                  <RefreshCw className="h-3.5 w-3.5 animate-spin" />
                  <span>Agent formulating baiting payload...</span>
                </div>
              )}
              <div ref={chatBottomRef} />
            </div>

            {/* Step Controls */}
            <div className="flex items-center justify-between border-t border-slate-800 bg-slate-900/70 p-3">
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={handleNextStep}
                  disabled={isSimulating || currentStepIndex >= mockHoneypotScript.length}
                  className="flex items-center gap-1.5 rounded-xl bg-purple-600 px-3.5 py-1.5 text-xs font-bold text-white shadow-md hover:bg-purple-500 disabled:opacity-50"
                >
                  <Send className="h-3.5 w-3.5" />
                  <span>{language === 'kn' ? 'ಮುಂದಿನ ಬಲೆ ಸಂಭಾಷಣೆ' : 'Engage Next Bait Step'}</span>
                </button>

                <button
                  type="button"
                  onClick={handleAutoRun}
                  disabled={isSimulating || currentStepIndex >= mockHoneypotScript.length}
                  className="flex items-center gap-1.5 rounded-xl border border-slate-700 bg-slate-800 px-3 py-1.5 text-xs font-semibold text-slate-200 hover:bg-slate-700 disabled:opacity-50"
                >
                  <Sparkles className="h-3.5 w-3.5 text-cyan-400" />
                  <span>{language === 'kn' ? 'ಸ್ವಯಂಚಾಲಿತ ರನ್' : 'Auto-Engage'}</span>
                </button>
              </div>

              <span className="font-mono text-[11px] text-slate-400">
                Step {currentStepIndex}/{mockHoneypotScript.length}
              </span>
            </div>
          </div>
        </div>

        {/* Right: Harvested IOC Ledger (5 cols) */}
        <div className="lg:col-span-5 flex flex-col gap-4">
          <div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5 backdrop-blur-md">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3 mb-3">
              <div>
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-200 flex items-center gap-1.5">
                  <ShieldAlert className="h-4 w-4 text-amber-400" />
                  <span>{language === 'kn' ? 'ಹೊರತೆಗೆದ ಮ್ಯೂಲ್ ವಿವರಗಳು' : 'Harvested Mule Accounts & IOCs'}</span>
                </h3>
                <span className="text-[10px] text-slate-400">
                  Ready for 1930 NCRP Freeze Dispatch
                </span>
              </div>
              <span className="rounded-full bg-amber-500/20 px-2 py-0.5 font-mono text-xs font-bold text-amber-400">
                {harvestedIOCs.length} Trapped
              </span>
            </div>

            {/* IOC List */}
            <div className="space-y-2.5 max-h-[380px] overflow-y-auto">
              {harvestedIOCs.map((ioc) => (
                <div
                  key={ioc.id}
                  className="rounded-xl border border-slate-800 bg-slate-950/70 p-3 transition-all hover:border-slate-700"
                >
                  <div className="flex items-center justify-between mb-1">
                    <span className="rounded bg-slate-800 px-1.5 py-0.5 font-mono text-[10px] font-bold text-cyan-300">
                      {ioc.type}
                    </span>
                    <span className="text-[10px] font-mono font-bold text-red-400">
                      Risk: {ioc.riskScore}/100
                    </span>
                  </div>

                  <div className="font-mono text-xs font-bold text-slate-100 break-all">
                    {ioc.value}
                  </div>

                  <div className="mt-2 flex items-center justify-between text-[10px] text-slate-400 font-sans border-t border-slate-800/80 pt-2">
                    <span>Archetype: {ioc.linkedScamArchetype}</span>
                    <button
                      type="button"
                      onClick={() => {
                        navigator.clipboard.writeText(ioc.value);
                        setCopied(true);
                        setTimeout(() => setCopied(false), 1500);
                      }}
                      className="text-cyan-400 hover:text-cyan-300 flex items-center gap-1 font-mono"
                    >
                      <Copy className="h-3 w-3" />
                      <span>{copied ? 'Copied' : 'Copy'}</span>
                    </button>
                  </div>
                </div>
              ))}
            </div>

            {/* Direct Escalation */}
            <div className="mt-4 pt-3 border-t border-slate-800">
              <button
                type="button"
                onClick={() => onNavigateTo('golden-hour')}
                className="w-full flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-red-600 to-rose-600 px-4 py-2.5 text-xs font-bold text-white shadow-lg shadow-red-600/30 hover:scale-[1.02] active:scale-98"
              >
                <Flame className="h-4 w-4 animate-pulse" />
                <span>{language === 'kn' ? 'ಈ ಮ್ಯೂಲ್ ಖಾತೆಗಳನ್ನು 1930 ನಲ್ಲಿ ತಕ್ಷಣ ಫ್ರೀಜ್ ಮಾಡಿ' : 'Dispatch Harvested IOCs to 1930 Freeze Desk'}</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
